///Fitur User
//Register Akun User
POST http://localhost:5003/register
Content-Type: application/json

{
    "username": "farskuy",
    "email": "farskuy@gmail.com",
    "gender": "Male",
    "password": "farskuy"
}

###
//Mencoba Register mengggunakan akun lain
POST http://localhost:5003/register
Content-Type: application/json

{
    "username": "ulalaaa",
    "email": "ulala@gmail.com",
    "gender": "Female",
    "password": "ulala123"
}

###
//Mencoba Register mengggunakan akun lain
POST http://localhost:5003/register
Content-Type: application/json

{
    "username": "denskuy",
    "email": "denskuy@gmail.com",
    "gender": "Male",
    "password": "denskuy123"
}

###
//Login Akun User
POST http://localhost:5003/login
Content-Type: application/json

{
    "email": "farskuy@gmail.com",
    "password": "farskuy"
}

###
//Login Akun User yang lain
POST http://localhost:5003/login
Content-Type: application/json

{
    "email": "inces@gmail.com",
    "password": "inces"
}

###
//Logout Akun User
POST http://localhost:5003/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5eSIsImVtYWlsIjoiZmFyc2t1eUBnbWFpbC5jb20iLCJnZW5kZXIiOiJGZW1hbGUiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIxVDE0OjU2OjE3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI3VDIzOjU4OjQxLjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODM5MDMyNCwiZXhwIjoxNzQ4MzkyMTI0fQ.S8w_BzKccNdYG-lST3HC0JCx5hw6rPZa1XWbrvrs7S4

###
//Update Data User
PUT http://localhost:5003/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIxVDE0OjU2OjE3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI3VDIzOjQ0OjMyLjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODM5MDEyMywiZXhwIjoxNzQ4MzkxOTIzfQ.vPooI9M7kfahi1QHPRdMLduPtWpL_Bq3_KClLfTst60
Content-Type: application/json

{
    "username": "farskuyy",
    "email": "farskuy@gmail.com",
    "gender": "Male",
    "password": "farskuy"
}

###
//Menambahkan Komentar pada suatu berita
POST http://localhost:5003/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJpbmNlcyIsImVtYWlsIjoiaW5jZXNAZ21haWwuY29tIiwiZ2VuZGVyIjoiRmVtYWxlIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yMlQwOToyMzozOC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yN1QyMzo1ODo1OS4wMDBaIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDgzOTA0NjAsImV4cCI6MTc0ODM5MjI2MH0.Jc9HfbQQ65wE3DrZKx_vzJxuvbz2MsJuUTD4Uqd81vQ

{
  "newsId": 13,
  "content": "Woilah"
}

//Menghapus Komentar dari suatu berita
###
DELETE http://localhost:5003/comments/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJpbmNlcyIsImVtYWlsIjoiaW5jZXNAZ21haWwuY29tIiwiZ2VuZGVyIjoiRmVtYWxlIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yMlQwOToyMzozOC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yN1QyMzo1ODo1OS4wMDBaIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDgzOTA0NjAsImV4cCI6MTc0ODM5MjI2MH0.Jc9HfbQQ65wE3DrZKx_vzJxuvbz2MsJuUTD4Uqd81vQ

//Mengedit Komentar dari sebuah berita
###
PUT http://localhost:5003/comments/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJpbmNlcyIsImVtYWlsIjoiaW5jZXNAZ21haWwuY29tIiwiZ2VuZGVyIjoiRmVtYWxlIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yMlQwOToyMzozOC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTozNjo0MC4wMDBaIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDc5MDY2MzYsImV4cCI6MTc0NzkwODQzNn0.5gxGdZ79ve7lXyL6H6VOle1M82JxU2ebY68S2fx82DI

{
  "newsId": 1,
  "content": "Kalo Kataku ya. awaoonajkfdnajkfbndkjlnvadsjkffnsbdkjlfndskjlfnasdjkfnbakjlfbndskjlfnbksdjnfkjf nmsbvkjsd c nflsdfnjklsdanfljksd sldf"
}

### Mengambil data komentar
GET http://localhost:5003/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJwcm9maWxlVXNlciI6IiIsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMjFUMTQ6NTY6MTcuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDUtMjVUMDM6MjI6MzQuMDAwWiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ4MTQ0NTQzLCJleHAiOjE3NDgxNDYzNDN9.3wDHrk4eKRDT75bgiptLUzF9wsheJzTtymuIiadbA_I

### Mengambil data komentar semua
GET http://localhost:5003/comments/news/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJwcm9maWxlVXNlciI6IiIsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMjFUMTQ6NTY6MTcuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDUtMjVUMDM6MjI6MzQuMDAwWiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ4MTQ0NTQzLCJleHAiOjE3NDgxNDYzNDN9.3wDHrk4eKRDT75bgiptLUzF9wsheJzTtymuIiadbA_I

###
//Memberikan Like Pada Berita
POST http://localhost:5003/news/liked
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJwcm9maWxlVXNlciI6IiIsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMjFUMTQ6NTY6MTcuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDUtMjVUMDU6MjM6NTEuMDAwWiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ4MTUwODA4LCJleHAiOjE3NDgxNTI2MDh9.oz7PJdTyjk8kdKYLphTDFwoCXqs7Uzpty4KTlbQ26KY

{
  "newsId": 12
}

###
//Melihat Daftar Berita yang disukai user
GET http://localhost:5003/news/liked/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJwcm9maWxlVXNlciI6IiIsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMjFUMTQ6NTY6MTcuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDUtMjVUMTA6MDE6MzcuMDAwWiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ4MTY3MzE4LCJleHAiOjE3NDgxNjkxMTh9.cKR_zVg1tcikoAXTNKqikIPFKgqA5djh5ifJoRZEQwg

###
//Menghapus Suka pada berita
DELETE http://localhost:5003/news/liked/8
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJwcm9maWxlVXNlciI6IiIsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMjFUMTQ6NTY6MTcuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDUtMjVUMDU6MjM6MDQuMDAwWiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ4MTUwNjMxLCJleHAiOjE3NDgxNTI0MzF9.ERD8LuzN33h3Pv7tMk-CXEeQmg2XeaWvKbU_uWb3OkU

### Melihat Daftar Cek status like
GET http://localhost:5003/news/liked/check/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJwcm9maWxlVXNlciI6IiIsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMjFUMTQ6NTY6MTcuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDUtMjVUMDg6NDA6NTcuMDAwWiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ4MTYzMzQyLCJleHAiOjE3NDgxNjUxNDJ9.bhBMmI-5j2rE-UD3ixrmTqMN5jQbfDvSOtBvysOGB9o

###
//Melihat Daftar Like di suatu berita
GET http://localhost:5003/news/likesCount/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJwcm9maWxlVXNlciI6IiIsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMjFUMTQ6NTY6MTcuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDUtMjVUMTA6MDE6MzcuMDAwWiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ4MTY3MzE4LCJleHAiOjE3NDgxNjkxMTh9.cKR_zVg1tcikoAXTNKqikIPFKgqA5djh5ifJoRZEQwg


//Melihat Daftar berita
###
GET http://localhost:5003/news
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIxVDE0OjU2OjE3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI3VDA5OjQ2OjA2LjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODMzOTQ2OCwiZXhwIjoxNzQ4MzQxMjY4fQ.psSxB-AkrVhW_dGyhRrPAGcT5PFPySDF0MTWYXcJ0A0
    
//Melihat Detail berita
###
GET http://localhost:5003/news/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIxVDE0OjU2OjE3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI3VDEwOjQxOjAxLjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODM0Mjc5NSwiZXhwIjoxNzQ4MzQ0NTk1fQ.Noss2BwRiIoc3DTT9C9ZiNa1Tbq3Rct0foWgb1JoVLo


///Fitur Admin
###
//Register Akun Admin
POST http://localhost:5003/register/admin
Content-Type: application/json

{
    "username": "admin2",
    "email": "admin2@gmail.com",
    "password": "admin2"
}

###
//Login Akun Admin
POST http://localhost:5003/login
Content-Type: application/json

{
    "email": "admin1@gmail.com",
    "password": "admin1"
}

###
//Logout Akun Admin
POST http://localhost:5003/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJhZG1pbjEiLCJlbWFpbCI6ImFkbWluMUBnbWFpbC5jb20iLCJwcm9maWxlQWRtaW4iOiIiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTI0VDIxOjAzOjE5LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI0VDIxOjAzOjE5LjAwMFoiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDgxNDM2NjMsImV4cCI6MTc0ODE0NTQ2M30.XtimvAPdq7oRrCj_Umf81BRf2o3PICKtCQZUV7ZEyQ4

###
//Update Data diri admin
PUT http://localhost:5000/admin/update
Authorization: Bearer <TOKEN_ADMIN>
Content-Type: multipart/form-data

{
    "username": "admin.com",
    "email": "admin@gmail.com",
    "password": "admin",
    "profileAdmin": "[file image (jpg/png)]"
}

###
//Membuat Kategori Berita
POST http://localhost:5003/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4MTE3NjU3LCJleHAiOjE3NDgxMjQ4NTd9.s1_E82kOj35qHugOxvpuwPLt9g9iz6RBfFWKDwmUR9A


{
  "category": "Lingkungan"
}

###
//Mengecek apakah kategori berhasil dibuat
GET http://localhost:5003/categories

###
//Mengedit Kategori
PUT http://localhost:5003/categories/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4MTE3NjU3LCJleHAiOjE3NDgxMjQ4NTd9.s1_E82kOj35qHugOxvpuwPLt9g9iz6RBfFWKDwmUR9A

{
  "category": "Linglung"
}

###
//Menghapus Kategori
DELETE http://localhost:5003/categories/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4MTE3NjU3LCJleHAiOjE3NDgxMjQ4NTd9.s1_E82kOj35qHugOxvpuwPLt9g9iz6RBfFWKDwmUR9A

###
//Menambahkan Data Berita
POST http://localhost:5003/news 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4MTE3NjU3LCJleHAiOjE3NDgxMjQ4NTd9.s1_E82kOj35qHugOxvpuwPLt9g9iz6RBfFWKDwmUR9A

//image_small:"/uploads/wleowelo.png"
{
  "author": "UIA Channel",
  "title": "3 Tersangka Kasus Kredit Sritex Dijebloskan ke Rutan Salemba",
  "url": "https://www.cnnindonesia.com/nasional/20250521222134-12-1231792/3-tersangka-kasus-kredit-sritex-dijebloskan-ke-rutan-salemba",
  "description": "Tiga tersangka kasus korupsi pemberian fasilitas kredit PT Sritex, ditahan di Rutan Salemba, Jakarta.",
  "iso_date": "2025-05-21T15:35:24.000Z",
  "image_small": "https://akcdn.detik.net.id/visual/2025/05/21/dirut-pt-sritex-iwan-setiawan-lukminto-ditahan-kejagung-1747841622564_169.jpeg?w=360&q=90",
  "image_large": "https://akcdn.detik.net.id/visual/2025/05/21/dirut-pt-sritex-iwan-setiawan-lukminto-ditahan-kejagung-1747841622564_169.jpeg?w=360&q=100",
  "categoryId": 3
}


###
//Hapus Data Berita
DELETE http://localhost:5003/news/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4MTE3NjU3LCJleHAiOjE3NDgxMjQ4NTd9.s1_E82kOj35qHugOxvpuwPLt9g9iz6RBfFWKDwmUR9A

//Edit Data Berita
###
PUT http://localhost:5003/news/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4MTE3NjU3LCJleHAiOjE3NDgxMjQ4NTd9.s1_E82kOj35qHugOxvpuwPLt9g9iz6RBfFWKDwmUR9A

{
  "author": "Cublacks News",
  "title": "3 Tersangka Kasus Kredit Sritex Dijebloskan ke Rutan Salemba",
  "url": "https://www.cnnindonesia.com/nasional/20250521222134-12-1231792/3-tersangka-kasus-kredit-sritex-dijebloskan-ke-rutan-salemba",
  "description": "Tiga tersangka kasus korupsi pemberian fasilitas kredit PT Sritex, ditahan di Rutan Salemba, Jakarta.",
  "iso_date": "2025-05-21T15:35:24.000Z",
  "image_small": "https://akcdn.detik.net.id/visual/2025/05/21/dirut-pt-sritex-iwan-setiawan-lukminto-ditahan-kejagung-1747841622564_169.jpeg?w=360&q=90",
  "image_large": "https://akcdn.detik.net.id/visual/2025/05/21/dirut-pt-sritex-iwan-setiawan-lukminto-ditahan-kejagung-1747841622564_169.jpeg?w=360&q=100",
  "categoryId": 3
}

###
//Menambahkan Komentar pada inputan admin
POST http://localhost:5003/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4MTE3NjU3LCJleHAiOjE3NDgxMjQ4NTd9.s1_E82kOj35qHugOxvpuwPLt9g9iz6RBfFWKDwmUR9A

{
  "newsId": 11,
  "content": "e eleh"
}

//Menghapus Komentar dari suatu berita
###
DELETE http://localhost:5003/comments/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJhZG1pbjEiLCJlbWFpbCI6ImFkbWluMUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDgxMjA2MDksImV4cCI6MTc0ODEyNzgwOX0.WBkLQ83IJGWyvg-YHxKHYGKWTPtpxrELP1J-xr2cq0E

//Mengedit Komentar dari sebuah berita
###
PUT http://localhost:5003/comments/14
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJhZG1pbjEiLCJlbWFpbCI6ImFkbWluMUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDgxMjA2MDksImV4cCI6MTc0ODEyNzgwOX0.WBkLQ83IJGWyvg-YHxKHYGKWTPtpxrELP1J-xr2cq0E

{
  "newsId": 1,
  "content": "mantap"
}

### Mengambil data komentar
GET http://localhost:5003/comments/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJwcm9maWxlVXNlciI6IiIsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMjFUMTQ6NTY6MTcuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDUtMjRUMTk6MTU6MTEuMDAwWiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ4MTE0ODMzLCJleHAiOjE3NDgxMTY2MzN9.mA6T9WTTtlGjScutbZC7jmWOFIFRTL7MeFxxXsfN32I

### Mengambil data komentar semua
GET http://localhost:5003/comments/news/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJhZG1pbjEiLCJlbWFpbCI6ImFkbWluMUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDgxMjA2MDksImV4cCI6MTc0ODEyNzgwOX0.WBkLQ83IJGWyvg-YHxKHYGKWTPtpxrELP1J-xr2cq0E
