///Fitur User
//Register Akun User
POST http://localhost:5003/register
Content-Type: application/json

{
    "username": "farskuy",
    "email": "farskuy@gmail.com",
    "gender": "Male",
    "password": "farskuy"
}

###
POST http://localhost:5003/register
Content-Type: application/json

{
    "username": "inces",
    "email": "inces@gmail.com",
    "gender": "Female",
    "password": "inces123"
}

###
//Login Akun User
POST http://localhost:5003/login
Content-Type: application/json

{
    "email": "farskuy@gmail.com",
    "password": "farskuy"
}
###
POST http://localhost:5003/login
Content-Type: application/json

{
    "email": "inces@gmail.com",
    "password": "inces"
}

###
//Logout Akun User
POST http://localhost:5003/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJpbmNlc3NzIiwiZW1haWwiOiJpbmNlc3NzQGdtYWlsLmNvbSIsImdlbmRlciI6IkZlbWFsZSIsInByb2ZpbGVVc2VyIjoiIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yMlQwOToyMzozOC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yMlQxNjoyMzoyNC4wMDBaIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDc5MzEzNzgsImV4cCI6MTc0NzkzMzE3OH0.-iQsVmFI1I-Hb6Xm8ulApWX9zkFO82WGHcf1f1LL9ZQ

###
//Update Data User
PUT http://localhost:5003/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJpbmNlc3NzIiwiZW1haWwiOiJpbmNlc3NzQGdtYWlsLmNvbSIsImdlbmRlciI6IkZlbWFsZSIsInByb2ZpbGVVc2VyIjoiIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yMlQwOToyMzozOC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yMlQxNjoyMzoyNC4wMDBaIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDc5MzEzNzgsImV4cCI6MTc0NzkzMzE3OH0.-iQsVmFI1I-Hb6Xm8ulApWX9zkFO82WGHcf1f1LL9ZQ
Content-Type: application/json

{
    "username": "inces",
    "email": "inces@gmail.com",
    "gender": "Female",
    "password": "inces",
    "profileUser": "meong.jpg"
}

###
//Menambahkan Komentar pada suatu berita
POST http://localhost:5003/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJpbmNlcyIsImVtYWlsIjoiaW5jZXNAZ21haWwuY29tIiwiZ2VuZGVyIjoiRmVtYWxlIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yMlQwOToyMzozOC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTozNjo0MC4wMDBaIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDc5MDY2MzYsImV4cCI6MTc0NzkwODQzNn0.5gxGdZ79ve7lXyL6H6VOle1M82JxU2ebY68S2fx82DI

{
  "newsId": 1,
  "content": "Kalo Menurutku sih gini ya bro. awaoonajkfdnajkfbndkjlnvadsjkffnsbdkjlfndskjlfnasdjkfnbakjlfbndskjlfnbksdjnfkjf nmsbvkjsd c nflsdfnjklsdanfljksd sldf"
}

//Menghapus Komentar dari suatu berita
###
DELETE http://localhost:5003/comments/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJpbmNlcyIsImVtYWlsIjoiaW5jZXNAZ21haWwuY29tIiwiZ2VuZGVyIjoiRmVtYWxlIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yMlQwOToyMzozOC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTozNjo0MC4wMDBaIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDc5MDY2MzYsImV4cCI6MTc0NzkwODQzNn0.5gxGdZ79ve7lXyL6H6VOle1M82JxU2ebY68S2fx82DI

//Mengedit Komentar dari sebuah berita
###
PUT http://localhost:5003/comments/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJpbmNlcyIsImVtYWlsIjoiaW5jZXNAZ21haWwuY29tIiwiZ2VuZGVyIjoiRmVtYWxlIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yMlQwOToyMzozOC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTozNjo0MC4wMDBaIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDc5MDY2MzYsImV4cCI6MTc0NzkwODQzNn0.5gxGdZ79ve7lXyL6H6VOle1M82JxU2ebY68S2fx82DI

{
  "newsId": 1,
  "content": "Kalo Kataku ya. awaoonajkfdnajkfbndkjlnvadsjkffnsbdkjlfndskjlfnasdjkfnbakjlfbndskjlfnbksdjnfkjf nmsbvkjsd c nflsdfnjklsdanfljksd sldf"
}

###
//Memberikan Like Pada Berita
POST http://localhost:5003/news/liked
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJwcm9maWxlVXNlciI6IiIsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMjFUMTQ6NTY6MTcuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDUtMjNUMTc6MDY6MjcuMDAwWiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ4MDIwMzEyLCJleHAiOjE3NDgwMjIxMTJ9.oCf1qDO-fqe48yMOyh1ckmSJu9g_hGmcrIpJ0dZ11qU

{
  "newsId": 8
}

###
//Melihat Daftar Berita yang disukai user
GET http://localhost:5003/news/liked
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJpbmNlcyIsImVtYWlsIjoiaW5jZXNAZ21haWwuY29tIiwiZ2VuZGVyIjoiRmVtYWxlIiwicHJvZmlsZVVzZXIiOiIiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIyVDA5OjIzOjM4LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI0VDE0OjE5OjQxLjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODA5NzgxNSwiZXhwIjoxNzQ4MDk5NjE1fQ.R4x_FLddimEMistKKVevYh7wdmMPbPnt797ozJP6wFg

###
//Menghapus Suka pada berita
DELETE http://localhost:5003/news/liked/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJwcm9maWxlVXNlciI6IiIsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMjFUMTQ6NTY6MTcuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDUtMjNUMTc6MDY6MjcuMDAwWiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ4MDIwMzEyLCJleHAiOjE3NDgwMjIxMTJ9.oCf1qDO-fqe48yMOyh1ckmSJu9g_hGmcrIpJ0dZ11qU

### Melihat Daftar Cek status like
GET http://localhost:5003/news/liked/check/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJpbmNlcyIsImVtYWlsIjoiaW5jZXNAZ21haWwuY29tIiwiZ2VuZGVyIjoiRmVtYWxlIiwicHJvZmlsZVVzZXIiOiIiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIyVDA5OjIzOjM4LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI0VDE0OjUxOjQ5LjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODA5OTI4NSwiZXhwIjoxNzQ4MTAxMDg1fQ.aSTyen6cTsfvfKIgqCpgbKCl754I3hpTOiso3QGgDlc

//Melihat Daftar berita
###
GET http://localhost:5003/news
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJwcm9maWxlVXNlciI6IiIsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMjFUMTQ6NTY6MTcuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDUtMjNUMDk6MTM6MzYuMDAwWiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ3OTkyMjYzLCJleHAiOjE3NDc5OTQwNjN9.BfA-70iMuMWjpNoFgbiy5O5QNS7hJk59vxaMxjzsByA

///Fitur Admin
###
//Register Akun Admin
POST http://localhost:5003/admin/register
Content-Type: application/json

{
    "username": "admin",
    "email": "admin@gmail.com",
    "password": "admin"
}

###
//Login Akun Admin
POST http://localhost:5003/admin/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin"
}

###

//Logout Akun Admin
POST http://localhost:5003/admin/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ3OTIwOTExLCJleHAiOjE3NDc5MjgxMTF9.EK85XXZbIYTY_15mF1tMNmHZrICGmbFxDrX66ZdwS9Q

###
//Update Data diri admin
PUT http://localhost:5000/admin/update
Authorization: Bearer <TOKEN_ADMIN>
Content-Type: multipart/form-data

{
    "username": "admin.com",
    "email": "admin@gmail.com",
    "password": "admin",
    "profileAdmin": "[file image (jpg/png)]"
}

###
//Membuat Kategori Berita
POST http://localhost:5003/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ3OTE0OTgyLCJleHAiOjE3NDc5MjIxODJ9.E6UAixDs8_7_Y4ZzKKm4bsezKawm0_0ZW95r-ewF1ag


{
  "category": "Masyarakat"
}

###
//Mengecek apakah kategori berhasil dibuat
GET http://localhost:5003/categories

###
//Mengedit Kategori
PUT http://localhost:5003/categories/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ3OTE0OTgyLCJleHAiOjE3NDc5MjIxODJ9.E6UAixDs8_7_Y4ZzKKm4bsezKawm0_0ZW95r-ewF1ag

{
  "category": "Korupsi"
}

###
//Menghapus Kategori
DELETE http://localhost:5003/categories/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ3OTE0OTgyLCJleHAiOjE3NDc5MjIxODJ9.E6UAixDs8_7_Y4ZzKKm4bsezKawm0_0ZW95r-ewF1ag

###
//Menambahkan Data Berita
POST http://localhost:5003/news 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ3OTA5Njc3LCJleHAiOjE3NDc5MTY4Nzd9.m_oonnNb13KYrTNozOqSSsSkolc9rsACshXPnimR1zM
//image_small:"/uploads/wleowelo.png"
{
  "author": "UIA Channel",
  "title": "Guru Besar UI: Kondisi PRT RI Banyak Dikritik Dunia Internasional",
  "url": "https://www.cnnindonesia.com/nasional/20250521084207-12-1231412/guru-besar-ui-kondisi-prt-ri-banyak-dikritik-dunia-internasional",
  "description": "Guru besar UI menyoroti perlindungan pekerja rumah tangga atau PRT di Indonesia yang minim regulasi. RUU PPRT diharapkan segera disahkan.",
  "iso_date": "2025-05-22T01:30:00.000Z",
  "image_small": "https://akcdn.detik.net.id/visual/2024/08/15/demo-tuntut-dpr-mengesahkan-ruu-perlindungan-prt-10_169.jpeg?w=360&q=90",
  "image_large": "https://akcdn.detik.net.id/visual/2024/08/15/demo-tuntut-dpr-mengesahkan-ruu-perlindungan-prt-10_169.jpeg?w=360&q=100",
  "categoryId": 3
}


###
//Hapus Data Berita
DELETE http://localhost:5003/news/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ3OTA5Njc3LCJleHAiOjE3NDc5MTY4Nzd9.m_oonnNb13KYrTNozOqSSsSkolc9rsACshXPnimR1zM

//Edit Data Berita
###
PUT http://localhost:5003/news/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4MDA5MTA4LCJleHAiOjE3NDgwMTYzMDh9.Ph-HFOvWqSSvYU7gWxWvxE2kmL6FZMgSp34CWA1sSZM

{
  "author": "Cublacks News",
  "title": "Korupsi Dana Hibah Jatim, KPK Sita Tanah Senilai Rp2 M di Pasuruan",
  "url": "https://www.cnnindonesia.com/nasional/20250522173309-12-1232145/korupsi-dana-hibah-jatim-kpk-sita-tanah-senilai-rp2-m-di-pasuruan",
  "description": "KPK menyita tanah senilai Rp2 miliar di Pasuruan terkait dugaan korupsi dana hibah. Lima saksi diperiksa dalam penyidikan kasus ini.",
  "iso_date": "2025-05-22T15:00:04.000Z",
  "image_small": "https://akcdn.detik.net.id/visual/2017/02/23/0cd938c1-a601-4d91-a192-c2caf42cb658_169.jpg?w=360&q=90",
  "image_large": "https://akcdn.detik.net.id/visual/2017/02/23/0cd938c1-a601-4d91-a192-c2caf42cb658_169.jpg?w=360&q=100",
  "categoryId": 4
}

