///Fitur User
//Register Akun User
POST http://localhost:5003/register
Content-Type: application/json

{
    "username": "farskuy",
    "email": "farskuy@gmail.com",
    "gender": "Male",
    "password": "farskuy"
}

###
//Mencoba Register mengggunakan akun lain
POST http://localhost:5003/register
Content-Type: application/json

{
    "username": "ulalaaa",
    "email": "ulala@gmail.com",
    "gender": "Female",
    "password": "ulala123"
}

###
//Mencoba Register mengggunakan akun lain
POST http://localhost:5003/register
Content-Type: application/json

{
    "username": "denskuy",
    "email": "denskuy@gmail.com",
    "gender": "Male",
    "password": "denskuy123"
}

###
//Login Akun User
POST http://localhost:5003/login
Content-Type: application/json

{
    "email": "farskuy@gmail.com",
    "password": "farskuy"
}

###
//Login Akun User yang lain
POST http://localhost:5003/login
Content-Type: application/json

{
    "email": "inces@gmail.com",
    "password": "inces"
}

###
//Logout Akun User
POST http://localhost:5003/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIxVDE0OjU2OjE3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA2LTAxVDE2OjE1OjMwLjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODgyODg1MiwiZXhwIjoxNzQ4ODMwNjUyfQ.CpomcvXQS1h5N6ZgeiPGhhJSba7ZH_qXpNtiglr_L6M

###
//Update Data User
PUT http://localhost:5003/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5eSIsImVtYWlsIjoiZmFyc2t1eUBnbWFpbC5jb20iLCJnZW5kZXIiOiJNYWxlIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yMVQxNDo1NjoxNy4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yOFQwMDoxMjo1MC4wMDBaIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDgzOTEyMjEsImV4cCI6MTc0ODM5MzAyMX0.JcjVLbPQt5vCZIU66HtkXSlXPRspHHG1e1ctOHA_wHM
Content-Type: application/json

{
    "username": "farskuyy",
    "email": "farskuy@gmail.com",
    "gender": "Male",
    "password": "farskuy"
}

###
//Menambahkan Komentar pada suatu berita
POST http://localhost:5003/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIxVDE0OjU2OjE3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA2LTAxVDE2OjE1OjMwLjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODgyODg1MiwiZXhwIjoxNzQ4ODMwNjUyfQ.CpomcvXQS1h5N6ZgeiPGhhJSba7ZH_qXpNtiglr_L6M

{
  "newsId": 13,
  "content": "Walaweeee"
}

//Menghapus Komentar dari suatu berita
###
DELETE http://localhost:5003/comments/100
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIxVDE0OjU2OjE3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI4VDAxOjI5OjQwLjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODQwMTU0MCwiZXhwIjoxNzQ4NDAzMzQwfQ.zlMwGpkxsikAQRepivgXe_gtmRj2oDmjGfDq9EXgVEg
//Mengedit Komentar dari sebuah berita
###
PUT http://localhost:5003/comments/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIxVDE0OjU2OjE3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI4VDAxOjI5OjQwLjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODQwMTU0MCwiZXhwIjoxNzQ4NDAzMzQwfQ.zlMwGpkxsikAQRepivgXe_gtmRj2oDmjGfDq9EXgVEg

{
  "newsId": 1,
  "content": "Amboyy"
}

### Mengambil data komentar
GET http://localhost:5003/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIxVDE0OjU2OjE3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI4VDAxOjI5OjQwLjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODQwMTU0MCwiZXhwIjoxNzQ4NDAzMzQwfQ.zlMwGpkxsikAQRepivgXe_gtmRj2oDmjGfDq9EXgVEg

### Mengambil data komentar 
GET http://localhost:5003/comments/news/60
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIxVDE0OjU2OjE3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI4VDAxOjI5OjQwLjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODQwMTU0MCwiZXhwIjoxNzQ4NDAzMzQwfQ.zlMwGpkxsikAQRepivgXe_gtmRj2oDmjGfDq9EXgVEg

###
//Memberikan Like Pada Berita
POST http://localhost:5003/news/liked
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIxVDE0OjU2OjE3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI4VDAzOjE1OjM3LjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODQwMzQxMCwiZXhwIjoxNzQ4NDA1MjEwfQ.hKkvwg-gPDyOhBebta11NcX11kkcx6Afw3u5TM33Kd8

{
  "newsId": 6
}

###
//Melihat Daftar Berita yang disukai user
GET http://localhost:5003/news/liked/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIxVDE0OjU2OjE3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI4VDAzOjE1OjM3LjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODQwMzQxMCwiZXhwIjoxNzQ4NDA1MjEwfQ.hKkvwg-gPDyOhBebta11NcX11kkcx6Afw3u5TM33Kd8

###
//Menghapus Suka pada berita
DELETE http://localhost:5003/news/liked/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIxVDE0OjU2OjE3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI4VDAzOjE1OjM3LjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODQwMzQxMCwiZXhwIjoxNzQ4NDA1MjEwfQ.hKkvwg-gPDyOhBebta11NcX11kkcx6Afw3u5TM33Kd8

### Melihat Daftar Cek status like
GET http://localhost:5003/news/liked/check/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIxVDE0OjU2OjE3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI4VDAzOjE1OjM3LjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODQwMzQxMCwiZXhwIjoxNzQ4NDA1MjEwfQ.hKkvwg-gPDyOhBebta11NcX11kkcx6Afw3u5TM33Kd8

###
//Melihat Daftar Like di suatu berita
GET http://localhost:5003/news/likesCount/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIxVDE0OjU2OjE3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI4VDAzOjE1OjM3LjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODQwMzQxMCwiZXhwIjoxNzQ4NDA1MjEwfQ.hKkvwg-gPDyOhBebta11NcX11kkcx6Afw3u5TM33Kd8

//Melihat Daftar berita
###
GET http://localhost:5003/news
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJwaG90byI6IiIsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMjFUMTQ6NTY6MTcuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDYtMDNUMTE6NTQ6MjcuMDAwWiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ4OTUxNzIwLCJleHAiOjE3NDg5NTE3NTB9.SawwwCpJIKqAG2a6Vo66-bZVKCI6lUwkIiSvhfxs5VY

//Melihat Detail berita
###
GET http://localhost:5003/news/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTIxVDE0OjU2OjE3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI4VDAzOjE1OjM3LjAwMFoiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0ODQwMzQxMCwiZXhwIjoxNzQ4NDA1MjEwfQ.hKkvwg-gPDyOhBebta11NcX11kkcx6Afw3u5TM33Kd8


///Fitur Admin
###
//Register Akun Admin
POST http://localhost:5003/register/admin
Content-Type: application/json

{
    "username": "admin4",
    "email": "admin4@gmail.com",
    "password": "admin4"
}

###
//Login Akun Admin
POST http://localhost:5003/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin"
}

###
//Logout Akun Admin
POST http://localhost:5003/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTowOTozNS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTowOTozNS4wMDBaIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4NDAzOTY0LCJleHAiOjE3NDg0MDU3NjR9.KPPhvQo0EFAfhQvGnAlpXatDM6OlrSBxzQLAlA_8h3o


###
PUT http://localhost:5003/user/profile-picture
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJwaG90byI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yMVQxNDo1NjoxNy4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yNlQxMTo1Mjo1MC4wMDBaIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDg4NTczNTIsImV4cCI6MTc0ODg1OTE1Mn0.htp2YxsG6Ta9vVcu96SOmhNdzySUTfoRLzmawgMWPKE
Content-Type: multipart/form-data
file: (pilih file image dari form data)

###
# //Update Data diri admin
# PUT http://localhost:5000/admin/update
# Authorization: Bearer <TOKEN_ADMIN>
# Content-Type: multipart/form-data

# {
#     "username": "admin.com",
#     "email": "admin@gmail.com",
#     "password": "admin",
#     "profileAdmin": "[file image (jpg/png)]"
# }

###
//Membuat Kategori Berita
POST http://localhost:5003/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTowOTozNS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTowOTozNS4wMDBaIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4OTQ0NDk4LCJleHAiOjE3NDg5NDQ1Mjh9.qZCy5wwnE8eMGKXbgGTiluevfo-sdxyKivQr7pGuUVc

{
  "category": "Global Warming"
}

###
//Mengecek apakah kategori berhasil dibuat
GET http://localhost:5003/categories/100

###
//Mengedit Kategori
PUT http://localhost:5003/categories/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTowOTozNS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTowOTozNS4wMDBaIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4NDA0MDI2LCJleHAiOjE3NDg0MDU4MjZ9.K2pL3WcWm546QAxuxo8ov2IwROA8zkeNKUx5Qhwn124

{
  "category": "Lingkungan"
}

###
//Menghapus Kategori
DELETE http://localhost:5003/categories/100
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTowOTozNS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTowOTozNS4wMDBaIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4NDA0MDI2LCJleHAiOjE3NDg0MDU4MjZ9.K2pL3WcWm546QAxuxo8ov2IwROA8zkeNKUx5Qhwn124

###
//Menambahkan Data Berita
POST http://localhost:5003/news 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTowOTozNS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTowOTozNS4wMDBaIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4NDA0MDI2LCJleHAiOjE3NDg0MDU4MjZ9.K2pL3WcWm546QAxuxo8ov2IwROA8zkeNKUx5Qhwn124

//image_small:"/uploads/wleowelo.png"
{
  "author": "UIA Channel",
  "title": "Anggota TNI AL Pembunuh Sales Mobil di Aceh Divonis Bui Seumur Hidup",
  "url": "https://www.cnnindonesia.com/nasional/20250527194454-12-1233885/anggota-tni-al-pembunuh-sales-mobil-di-aceh-divonis-bui-seumur-hidup",
  "description": "Anggota TNI AL Dede Irawan divonis seumur hidup atas pembunuhan sales mobil di Aceh.",
  "iso_date": "2025-05-21T15:35:24.000Z",
  "image_small": "https://akcdn.detik.net.id/visual/2020/06/22/ilustrasi-penusukan-4_169.jpeg?w=360&q=90",
  "image_large": "https://akcdn.detik.net.id/visual/2020/06/22/ilustrasi-penusukan-4_169.jpeg?w=360&q=100",
  "categoryId": 3
}


###
//Hapus Data Berita
DELETE http://localhost:5003/news/100
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTowOTozNS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTowOTozNS4wMDBaIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4NDA0MDI2LCJleHAiOjE3NDg0MDU4MjZ9.K2pL3WcWm546QAxuxo8ov2IwROA8zkeNKUx5Qhwn124

//Edit Data Berita
###
PUT http://localhost:5003/news/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTowOTozNS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yMlQwOTowOTozNS4wMDBaIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4NDA0MDI2LCJleHAiOjE3NDg0MDU4MjZ9.K2pL3WcWm546QAxuxo8ov2IwROA8zkeNKUx5Qhwn124

{
  "author": "Cublacks News",
  "title": "3 Tersangka Kasus Kredit Sritex Dijebloskan ke Rutan Salemba",
  "url": "https://www.cnnindonesia.com/nasional/20250521222134-12-1231792/3-tersangka-kasus-kredit-sritex-dijebloskan-ke-rutan-salemba",
  "description": "Tiga tersangka kasus korupsi pemberian fasilitas kredit PT Sritex, ditahan di Rutan Salemba, Jakarta.",
  "iso_date": "2025-05-21T15:35:24.000Z",
  "image_small": "https://akcdn.detik.net.id/visual/2025/05/21/dirut-pt-sritex-iwan-setiawan-lukminto-ditahan-kejagung-1747841622564_169.jpeg?w=360&q=90",
  "image_large": "https://akcdn.detik.net.id/visual/2025/05/21/dirut-pt-sritex-iwan-setiawan-lukminto-ditahan-kejagung-1747841622564_169.jpeg?w=360&q=100",
  "categoryId": 3
}

###
//Menambahkan Komentar pada inputan admin
POST http://localhost:5003/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4MTE3NjU3LCJleHAiOjE3NDgxMjQ4NTd9.s1_E82kOj35qHugOxvpuwPLt9g9iz6RBfFWKDwmUR9A

{
  "newsId": 11,
  "content": "e eleh"
}

//Menghapus Komentar dari suatu berita
###
DELETE http://localhost:5003/comments/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJhZG1pbjEiLCJlbWFpbCI6ImFkbWluMUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDgxMjA2MDksImV4cCI6MTc0ODEyNzgwOX0.WBkLQ83IJGWyvg-YHxKHYGKWTPtpxrELP1J-xr2cq0E

//Mengedit Komentar dari sebuah berita
###
PUT http://localhost:5003/comments/14
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJhZG1pbjEiLCJlbWFpbCI6ImFkbWluMUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDgxMjA2MDksImV4cCI6MTc0ODEyNzgwOX0.WBkLQ83IJGWyvg-YHxKHYGKWTPtpxrELP1J-xr2cq0E

{
  "newsId": 1,
  "content": "mantap"
}

### Mengambil data komentar
GET http://localhost:5003/comments/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYXJza3V5IiwiZW1haWwiOiJmYXJza3V5QGdtYWlsLmNvbSIsImdlbmRlciI6Ik1hbGUiLCJwcm9maWxlVXNlciI6IiIsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMjFUMTQ6NTY6MTcuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDUtMjRUMTk6MTU6MTEuMDAwWiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ4MTE0ODMzLCJleHAiOjE3NDgxMTY2MzN9.mA6T9WTTtlGjScutbZC7jmWOFIFRTL7MeFxxXsfN32I

### Mengambil data komentar semua
GET http://localhost:5003/comments/news/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJhZG1pbjEiLCJlbWFpbCI6ImFkbWluMUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDgxMjA2MDksImV4cCI6MTc0ODEyNzgwOX0.WBkLQ83IJGWyvg-YHxKHYGKWTPtpxrELP1J-xr2cq0E
